#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
use_brew=1
default_agent=""

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --no-brew)
      use_brew=0
      shift
      ;;
    --default-agent)
      [[ "$#" -ge 2 ]] || {
        echo "--default-agent requires a value" >&2
        exit 2
      }
      default_agent="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "Maestro currently supports macOS only." >&2
  exit 1
fi

if [[ "$use_brew" -eq 1 ]]; then
  if ! command -v brew >/dev/null 2>&1; then
    echo "Install Homebrew from https://brew.sh, then re-run install.sh." >&2
    exit 1
  fi
  brew bundle --file "$ROOT/Brewfile"
fi

for command in herdr node cargo; do
  command -v "$command" >/dev/null 2>&1 || {
    echo "Missing required command: $command" >&2
    exit 1
  }
done

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
maestro_home="$config_home/maestro"
herdr_home="$config_home/herdr"
bin_home="$HOME/.local/bin"
mkdir -p "$maestro_home" "$maestro_home/agents-local" "$herdr_home" "$bin_home"

ln -sfn "$ROOT/config/wezterm/wezterm.lua" "$maestro_home/wezterm.lua"
ln -sfn "$ROOT/agents" "$maestro_home/agents"

if [[ -n "$default_agent" ]]; then
  printf '%s\n' "$default_agent" > "$maestro_home/default-agent"
elif [[ ! -f "$maestro_home/default-agent" ]]; then
  cp "$ROOT/config/maestro/default-agent" "$maestro_home/default-agent"
fi

for command in maestro ai maestro-agent maestro-herdr; do
  ln -sfn "$ROOT/bin/$command" "$bin_home/$command"
done

herdr_config="$herdr_home/config.toml"
if [[ -f "$herdr_config" ]] && ! grep -Fq 'Generated by Maestro' "$herdr_config"; then
  cp "$herdr_config" "$herdr_config.backup.$(date +%Y%m%d%H%M%S)"
fi
escaped_agent="$(printf '%s' "$bin_home/maestro-agent" | sed 's/[\/&]/\\&/g')"
sed "s/@MAESTRO_AGENT@/$escaped_agent/g" \
  "$ROOT/config/herdr/config.toml.in" > "$herdr_config"

"$ROOT/scripts/build-app.sh"
"$ROOT/scripts/install-herdr-plugins.sh"
herdr server reload-config

if command -v copilot >/dev/null 2>&1 || [[ -d "$HOME/.copilot" ]]; then
  "$ROOT/scripts/install-copilot-integration.sh"
fi

git -C "$ROOT" config core.hooksPath .githooks
"$ROOT/scripts/check-public.sh"
echo
echo "Maestro is installed. Ensure $bin_home is on PATH, then run: maestro"
